//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CuteSqlite.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_QDIALOG_DIALOG              203
#define IDD_DIALOG1                     205
#define IDD_QFORM_DIALOG                205

// LeftTreeView ACCELERATORS
#define LEFT_TREEVIEW_ACCEL             32776

#define DATABASE_CREATE_ID              WM_USER + 360
#define DATABASE_OPEN_ID				DATABASE_CREATE_ID + 1
#define DATABASE_REFRESH_ID				DATABASE_CREATE_ID + 2
#define DATABASE_DELETE_ID				DATABASE_CREATE_ID + 3
#define DATABASE_COPY_ID				DATABASE_CREATE_ID + 4
#define DATABASE_EXPORT_AS_SQL_ID		DATABASE_CREATE_ID + 5
#define DATABASE_IMPORT_FROM_SQL_ID		DATABASE_CREATE_ID + 6

#define TABLE_OPEN_ID					WM_USER + 380
#define TABLE_CREATE_ID					TABLE_OPEN_ID + 1
#define TABLE_ALTER_ID					TABLE_OPEN_ID + 2
#define TABLE_RENAME_ID					TABLE_OPEN_ID + 3
#define TABLE_TRUNCATE_ID				TABLE_OPEN_ID + 4
#define TABLE_DROP_ID					TABLE_OPEN_ID + 5
#define TABLE_COPY_ID					TABLE_OPEN_ID + 6
#define TABLE_SHARDING_ID				TABLE_OPEN_ID + 7
#define TABLE_EXPORT_ID					TABLE_OPEN_ID + 8
#define TABLE_IMPORT_FROM_SQL_ID		TABLE_OPEN_ID + 9
#define TABLE_IMPORT_FROM_CSV_ID		TABLE_OPEN_ID + 10

// RightWorkView ACCELERATORS
#define RIGHT_WORKVIEW_ACCEL            32777
#define DATABASE_EXEC_SQL_ID			WM_USER + 50
#define DATABASE_EXEC_ALL_ID			DATABASE_EXEC_SQL_ID + 1
#define DATABASE_EXPLAIN_SQL_ID			DATABASE_EXEC_SQL_ID + 2
#define DATABASE_QUERY_ID				DATABASE_EXEC_SQL_ID + 3
#define DATABASE_HISTORY_ID				DATABASE_EXEC_SQL_ID + 4
#define DATABASE_SAVE_ID				DATABASE_EXEC_SQL_ID + 5
#define DATABASE_SAVE_ALL_ID			DATABASE_EXEC_SQL_ID + 6

// ResultListPage ACCELERATORS
#define RESULT_LIST_PAGE_ACCEL			32778
#define LISTVIEW_EXPORT_ID				WM_USER + 70
#define LISTVIEW_COPY_ID				LISTVIEW_EXPORT_ID + 1
#define LISTVIEW_FILTER_ID				LISTVIEW_EXPORT_ID + 2
#define LISTVIEW_REFRESH_ID				LISTVIEW_EXPORT_ID + 3
#define LISTVIEW_NEW_ROW_ID				LISTVIEW_EXPORT_ID + 4
#define LISTVIEW_COPY_ROW_ID			LISTVIEW_EXPORT_ID + 5
#define LISTVIEW_SAVE_ID				LISTVIEW_EXPORT_ID + 6
#define LISTVIEW_DELETE_ID				LISTVIEW_EXPORT_ID + 7
#define LISTVIEW_CANCEL_ID				LISTVIEW_EXPORT_ID + 8
#define COPY_ALL_ROWS_TO_CLIPBOARD_ID	WM_USER + 340
#define COPY_SEL_ROWS_TO_CLIPBOARD_ID	WM_USER + 341
#define COPY_ALL_ROWS_AS_SQL_ID			WM_USER + 342
#define COPY_SEL_ROWS_AS_SQL_ID			WM_USER + 343

// QMessageBox ACCELERATORS
#define QMESSAGE_BOX_ACCEL				32779
#define CUSTOMER_FORM_YES_ID			WM_USER + 40
#define CUSTOMER_FORM_NO_ID				CUSTOMER_FORM_YES_ID + 1

// QDIALOG ACCELERATORS
#define QDIALOG_ACCEL					32780
#define QDIALOG_YES_ID					WM_USER + 81
#define	QDIALOG_NO_ID					QDIALOG_YES_ID + 1

// RightAnalysisView ACCELERATORS
#define RIGHT_ANALYSIS_VIEW_ACCEL       32781
#define ANALYSIS_SQL_LOG_ID				WM_USER + 150
#define ANALYSIS_ADD_SQL_TO_ANALYSIS_ID	ANALYSIS_SQL_LOG_ID + 1
#define ANALYSIS_SAVE_ID				ANALYSIS_SQL_LOG_ID + 2
#define ANALYSIS_SAVE_ALL_ID			ANALYSIS_SQL_LOG_ID + 3

#define LEFT_NAVIGATION_VIEW_ACCEL       32782
#define ANALYSIS_OPEN_PERF_REPORT_ID	WM_USER + 510
#define ANALYSIS_DROP_PERF_REPORT_ID	WM_USER + 511
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
